name: eclipse_app
description: "Student Flutter movie catalog app with auth, favorites, and a user profile."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_loading_screen: ^0.0.3
  supabase_flutter: ^2.12.0
  shared_preferences: ^2.5.4
  salomon_bottom_bar: ^3.3.2
  image_picker: ^1.2.1
  path: ^1.9.1
  easy_stars: ^1.0.9
  flick_video_player: ^0.9.0
  video_player: ^2.11.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo_main.png"

flutter:
  uses-material-design: true

  assets:
    - images/background_logo.png
    - images/logo.png
